config/routes.rb
DevWebsite::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "home#index"
  
  match "about" => "about#show"
  
  resources :blogs
  resources :portfolios
  resources :about
  resources :contacts
  
  
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/blog.rb
class Blog < ActiveRecord::Base

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base

has_attached_file :photo, :styles => { :medium => "224x125#",
                                       :large => "295x166#"
                                       }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  
  def show
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
 
  def contact
    @contact = Contact.new(params[:contact])
    @contact.save
  end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index
    @blogs = Blog.all
  end
  
  def create
    @blog = Blog.new(params[:blog])
    #cleanly supporting multiple sets of view logic within the same action via XML or JSON
    respond_to do |format|
      if @blog.save
        format.html do
          redirect_to(@blog,
                      :notice => 'Blog was successfully created.')
        end
        format.xml do
          render :xml => @blog,
                 :status => :created,
                 :location => @blog
        end
      else
        format.html { render :new }
        format.xml do 
          render :xml => @blog.errors,
                 :status => :unprocessable_entity
        end
      end
    end
  end
  
  def show
    @blog = Blog.find(params[:id])
  end
  

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  def index
     @contacts = Contact.all
   end

   def new
     @contact = Contact.new
   end

   def create
     @contact = Contact.new(params[:contact])
     if @contact.save
       # Tell the ContactMailer to send the contact_email after save
       ContactMailer.contact_email(@contact).deliver
       
       redirect_to root_url, notice: "Contact was successfully created"
     else
       render action:"new"
     end
   end

   def show
     @contact = Contact.find(params[:id])
   end

   def edit
     @contact = Contact.find(params[:id])
   end

   def destroy
     @contact = Contact.find(params[:id])
     @contact.destroy
   end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contacts = Contact.new
  end
  
  def update
    
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  
  def index
    @portfolios = Portfolio.all
  end
  
  def new
    @portfolio = Portfolio.new
  end 
  
  def create
    @portfolio = Portfolio.new(params[:portfolio])
    if @portfolio.save 
      redirect_to root_url, notice: "portfolio saved"
    else
      render action:new
    end
  end
  
  def show
    @portfolio = Portfolio.find(params[:id])
  end
  
  def edit
    @portfolio = Portfolio.find(prams[:id])
  end 
  
  def destory
    @portfolio = Portfolio.   find(params[:id])
    @portfolio.destroy
    redirect_to root_url, notice: "portfolio destroyed"
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def contact
    @contact = Contact.new(params[:contact])
    @contact.save
  end
  
  def coderay(text)
      text.gsub(/\<code( lang="(.+?)")?\>(.+?)\<\/code\>/m) do
        CodeRay.scan($3, $2).div(:css => :class)
      end
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/about/show.html.erb
<div class="page_container">
  <div class="left_column">
    <h1><%= image_tag('Robert.jpg') %></h1>
    <h3>Name</h3>
      <p>Robert Stevenson</p>
    <h3>Phone</h3>
      <p>314.853.2202</p>
    <h3>Email</h3>
      <p>rstevenson542@gmail.com</p>
    <h3>Social Media</h3>
      <p><%= link_to image_tag("facebook.png"), "http://www.facebook.com" %><%= link_to image_tag("linkedin.png"), "http://www.linkedin.com/pub/robert-stevenson/20/a48/10a" %><%= link_to image_tag("twitter.png"), "https://twitter.com/#!/robonrails" %></p>
  </div left-column>
  <div class="right_column">
      <h1>Personal Summary</h1>
        <p>When I was five years old, I received my first computer as a birthday gift, and from that moment on, computers and technology has been my obsession. Upon graduating high school, I moved to Minneapolis, MN where I attended the University of Minnesota and studied political science and global politics. I walked on to the University's baseball team my freshman year; the time commitment of Division I college athletics helped me to realize the importance of a strong work ethic towards accomplishing your goals. During my sophomore year, I launched my first website selling digital sound libraries to hip-hop music producers. Within a few days, the company was profitable and generating enough income for me to quit my job working on campus.</p>

        <p>My introduction to web development began at Code Academy, an intensive twelve week program that teaches web development using the Ruby on Rails web application framework. During my time at Code Academy, I had the unique opportunity to interact with the best in Chicago's entrepreneurial and tech community. I developed solid foundations in Ruby on Rails, HTML 5 ,  CSS, and jQuery. I was also exposed to pair programming, test driven development, and agile software development.</p> 

        <p>Currently I live in St. Louis, MO where I work as a freelance web developer. A variety of daily tasks for me include back end development, front end development, project management, web design, running internet marketing campaigns and perhaps most importantly: maintaining my status as the self-proclaimed Madden champion of the world.</p>
      <h1>Outside of the Office</h1>
        <p>When I am not working, I enjoy spending time traveling and taking road trips. Lately, I have been on a quest to taste America's best craft beers. Apart from web development, I also enjoy listening to and creating hip-hop music. My favorite artists include A Tribe Called Quest, The Pharcyde, and Slum Village. I am happiest when I am surrounded by good friends, eating tasty food,  just enjoying the moment. </p>
  </div right-column>  
</div page_container>
<div class="about_footer">
</div footer>

app/views/blogs/_form.html.erb
<div class="form">
<%= form_for(@blog) do |f| %>
  
  <div class="name">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="email">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="password">
    <%= f.label :post %><br />
    <%= f.text_area :post %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/blogs/edit.html.erb
<%= render "form" %>

app/views/blogs/index.html.erb
<div class="blog_wrapper">
   <% @blogs.each do |blog| %>
        <h3 class="datetime"><%= l(blog.created_at, :format => :short) %></h3>
        <h2 class="blog_header"><%= link_to blog.title, blog_path(blog) %></h2>
        <p class="blog_main"><%=raw coderay(blog.post) %></p><br/>
    <% end %>
</div wrapper>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/blogs/show.html.erb
<div class="blog_wrapper">
        <h3 class="datetime"><%= l(@blog.created_at, :format => :short) %></h3>
        <h2 class="blog_header"><%= @blog.title %></h2>
        <p class="blog_main"><%= coderay(@blog.post) %></li></p><br/>
</div wrapper>

app/views/contacts/_form.html.erb
<form id="contact">
  <%= form_for(@contacts) do |f| %>
  <fieldset id="inputs">
    <h1>Hire Me</h1>
    <div class="name"><%= f.text_field :name, :placeholder => "Name  (ex: John Doe)" %></div>
    <div class="email"><%= f.text_field :email, :placeholder => "Email  (ex: jdoe@fubar.com)"%></div>
    <div class="description"><%= f.text_area :description, :placeholder => "Description  (Timeframe, Budget, Project Summary)" %></div>
    <div id="submit"><%= f.submit 'Submit', :class => 'button' %></div>
  </fieldset>
  <% end %>
</form>

app/views/home/index.html.erb
<div class="macbook"> 
<%= image_tag("Macbook.jpg", :alt => "Development Projects") %>
</div>

<div class="front_text">
  <h2>Clean, modern web development.</h2>
</div>
<div class="subtitle">
  <h2>I'm Robert, and I make creative content for the world wide web.</h2>
</div>
<div class="dots">
  <h3>..............................................</h3>
</div>


<%= render :partial => 'contacts/form', :object => @contacts %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href='http://fonts.googleapis.com/css?family=Oxygen|Ruda|Karla|Open+Sans+Condensed:300|Share' rel='stylesheet' type='text/css'>
  <title>DevWebsite</title>
  <%= stylesheet_link_tag    "application", "coderay", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">
      <div id="header" class="container_24 clearfix">
          <div id="logo" class="grid_7">
            <h1>
              <%= image_tag("logo.jpg", :alt => "logo")%>
            </h1>
          </div logo>
          <div id="nav" class="grid_17">  
            <ul>
              <li id="nav-home"><%= link_to 'Home', root_url %></li>
              <li id="nav-blog"><%= link_to 'Blog', blogs_path %></li>
              <li id="nav-portfolio"><%= link_to 'Portfolio', portfolios_path %></li>
              <li id="nav-about"><%= link_to 'About', about_path %></li>
            </ul>
          </div nav>  
        </div header>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
        <div class="spacer">
        </div spacer>
    </div wrapper>
    <div id="footer">
        <div class="left">
          <h2>©Bradford & Morgan Logistics</h2>
          <h3>rstevenson542@gmail.com</h3>
        </div>
    </div footer>
</body>
</html>

app/views/portfolios/_form.html.erb
<div class="form">
<%= form_for(@portfolio) do |f| %>
  
  <div class="name">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="email">
    <%= f.label :context %><br />
    <%= f.text_field :context %>
  </div>
  <div class="password">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/portfolios/edit.html.erb
<%= @portfolio.title %> <br/>
<%= @portfolio.context %> <br/>
<%= @portfolio.description %> <br/>

app/views/portfolios/index.html.erb
<div class="page_container">
      <% @portfolios.each do |portfolio| %>
      <div class="item">
          <div class="img">
              <%= link_to(content_tag(:span) + image_tag(portfolio.photo.url(:medium)), portfolio_url(portfolio)) %>
          </div img>
          <div class="item_info">
            <h3><%= link_to portfolio.title, portfolio_url(portfolio) %></h3>
            <p><%= portfolio.context %></p>
          </div item_info>  
      </div item>
      <% end %>
</div page_container>
<div class="about_footer">
</div footer>

app/views/portfolios/new.html.erb
<%= render 'form' %>

app/views/portfolios/show.html.erb
<div class="page_container">
  <div class="left_column">
    <h1><%= image_tag(@portfolio.photo.url(:large)) %></h1>
    <h3>Project</h3>
      <p><%= @portfolio.title %></p>
    <h3>Github</h3>
      <p><%= @portfolio.github %></p>
  </div show_photo>
  <div class="right_column">
    <h1>Project Description</h1>
      <p><%= @portfolio.description %></p>
    <h1>Services</h1>
      <p><%= @portfolio.services %></p>
    <h1>Tools</h1>
      <p><%= @portfolio.tools %></p>
  </div>
</div page_container>
<div class="about_footer">
</div footer>